Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -57,19 +57,25 @@ jobs:
       run: |
         # stop on linter problems above 
         pylint . --recursive=y --disable=W0511,R0801 --score=y --report=y ; echo "::set-output name=linter::$?" ; echo "::set-output name=foo::bar"
-    - name: Pass or fail
-      run: |
-        echo "${{ steps.linting.outputs.linter }}"
-        echo "${{ steps.linting.outputs.foo }}"
-        if [[ ${{ steps.linting.outputs.linter }} != 0 ]]; then
-          if [[ ${{ steps.linting.output.linter }} -gt 7 ]]; then
-            # anything below Warning level
-            echo "Exit 0!"
-            exit 0
-          else
-            echo "Exit 1!"
-            exit 1
-          fi
-        else
-          exit 0
-        fi
+    #- name: Pass or fail
+    #  run: |
+    #    echo "${{ steps.linting.outputs.exitcode }}"
+    #    echo "${{ steps.linting.outputs.exitcode }}"
+    #    if [[ ${{ steps.linting.outputs.linter }} != 0 ]]; then
+    #      if [[ ${{ steps.linting.output.linter }} -gt 7 ]]; then
+    #        # anything below Warning level
+    #        echo "Exit 0!"
+    #        exit 0
+    #      else
+    #        echo "Exit 1!"
+    #        exit 1
+    #      fi
+    #    else
+    #      exit 0
+    #    fi
+    - name: Another Test
+    - if: steps.linting.outputs.exitcode != '0'
+      run: echo "I ran !" ; exit 1
+    - name: Another Test
+    - if: steps.linting.outputs.exitcode == '0'
+      run: echo "I ran !" ; exit 1
